export default function getAllProducts() {
  return [
    {
      id: 'CLO-MEN-001',
      slug: 'casual-shirt-men',
      name: "Casual Shirt",
      category: `Men's Clothing`,
      categorySlug: 'men-clothing',
      price: 199_000,
      stock: 50,
      imageUrl: '/assets/images/casualmen.jpg',
      description: `Casual shirt pria dengan bahan berkualitas tinggi yang nyaman dipakai sehari-hari.`,
    },
    {
      id: 'CLO-MEN-002',
      slug: 'formal-shirt-men',
      name: "Formal Shirt",
      category: `Men's Clothing`,
      categorySlug: 'men-clothing',
      price: 299_000,
      stock: 30,
      imageUrl: '/assets/images/formalmen.jpg',
      description: `Kemeja formal pria cocok untuk acara resmi maupun kerja.`,
    },
    {
      id: 'CLO-WOMEN-001',
      slug: 'summer-dress-women',
      name: "Summer Dress",
      category: `Women's Clothing`,
      categorySlug: 'women-clothing',
      price: 249_000,
      stock: 70,
      imageUrl: '/assets/images/dress.jpg',
      description: `Gaun musim panas wanita dengan desain stylish dan bahan nyaman.`,
    },
    {
      id: 'CLO-WOMEN-002',
      slug: 'blouse-women',
      name: "Blouse",
      category: `Women's Clothing`,
      categorySlug: 'women-clothing',
      price: 179_000,
      stock: 40,
      imageUrl: '/assets/images/blouse.jpg',
      description: `Blus wanita dengan potongan modern dan bahan ringan.`,
    },
    {
      id: 'CLO-UNISEX-001',
      slug: 'hoodie-unisex',
      name: "Hoodie",
      category: `Unisex Clothing`,
      categorySlug: 'unisex-clothing',
      price: 279_000,
      stock: 25,
      imageUrl: '/assets/images/hoodie.jpg',
      description: `Hoodie unisex dengan desain minimalis dan bahan hangat.`,
    },
  ];
}
